// ============================================================
//  GODEYE — Intel Report Generator & Screenshot
// ============================================================
const ReportTool = (() => {
  function _generate() {
    const now = new Date();
    const c = STATE.center;
    const lines = [
      '╔══════════════════════════════════════════════════╗',
      '║         GODEYE INTELLIGENCE REPORT            ║',
      '║         UNCLASSIFIED // DEMONSTRATION            ║',
      '╚══════════════════════════════════════════════════╝',
      '',
      `TIMESTAMP:    ${now.toUTCString()}`,
      `LOCAL TIME:   ${now.toLocaleString()}`,
      `REPORT ID:    WV-${Date.now()}`,
      '',
      '══ MAP VIEW ═══════════════════════════════════════',
      `MODE:         ${STATE.mapMode.toUpperCase()}`,
      `CENTER:       ${c.lat.toFixed(5)}°, ${c.lng.toFixed(5)}°`,
      `ZOOM:         ${STATE.zoom?.toFixed(1) || '--'}`,
      '',
      '══ ACTIVE DATA LAYERS ════════════════════════════',
      ...Object.entries(STATE.layers)
        .filter(([, v]) => v.active)
        .map(([id, v]) => `  ${v.icon} ${v.label.padEnd(20)} ${v.count || 0} assets — ${v.online ? 'LIVE' : 'OFFLINE'}`),
      '',
      '══ ASSET COUNTS (CURRENT) ══════════════════════',
      `  ✈ Aircraft tracked:    ${STATE.counts.aircraft || 0}`,
      `  ⛴ Vessels tracked:     ${Object.keys(STATE.data.ships || {}).length}`,
      `  🛰 Satellites tracked: ${STATE.counts.satellites || 0}`,
      `  ⚔ Conflict events:     ${STATE.counts.conflicts || 0}`,
      `  🌍 Earthquakes (24h):  ${STATE.counts.earthquakes || 0}`,
      `  🕷 Cyber threats:      ${STATE.counts.cyber || 0}`,
      '',
      `  THREAT LEVEL: DEFCON ${STATE.threatLevel}`,
      '',
      '══ TOP 5 INTELLIGENCE ITEMS ═══════════════════',
      ...STATE.data.newsArticles.slice(0, 5).map((a, i) => `  ${i+1}. [${a.category}] ${a.title?.substring(0, 60)}\n     Source: ${a.source} | ${GEO.timeAgo(a.date)}`),
      '',
      '══ RECENT SIGINT LOG (LAST 10) ═════════════════',
      ...STATE.data.sigintLog.slice(0, 10).map(e => `  [${new Date(e.ts).toISOString().slice(11,19)}Z] [${e.cat}] ${e.msg}`),
      '',
      '══ END OF REPORT ════════════════════════════════',
      `GENERATED BY: GODEYE GEOSPATIAL INTELLIGENCE SYSTEM`,
    ];

    const text = lines.join('\n');
    const blob = new Blob([text], { type: 'text/plain' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = `GODEYE-intel-${Date.now()}.txt`;
    a.click();

    EventBus.emit('sigint:log', { cat: 'REPORT', msg: 'INTELLIGENCE REPORT GENERATED AND DOWNLOADED' });
  }

  async function _screenshot() {
    EventBus.emit('sigint:log', { cat: 'CAPTURE', msg: 'INITIATING SCREEN CAPTURE...' });
    try {
      const canvas = await html2canvas(document.body, {
        useCORS: false,
        allowTaint: true,
        scale: 1,
        logging: false,
      });

      // Watermark
      const ctx = canvas.getContext('2d');
      const ts = new Date().toISOString();
      ctx.fillStyle = 'rgba(0,0,0,0.5)';
      ctx.fillRect(10, canvas.height - 38, 520, 28);
      ctx.fillStyle = '#00ff41';
      ctx.font = '13px Share Tech Mono';
      ctx.fillText(`GODEYE // UNCLASSIFIED // ${ts}`, 15, canvas.height - 18);

      canvas.toBlob(blob => {
        const a = document.createElement('a');
        a.href = URL.createObjectURL(blob);
        a.download = `GODEYE-capture-${Date.now()}.png`;
        a.click();
      }, 'image/png');

      EventBus.emit('sigint:log', { cat: 'CAPTURE', msg: 'SCREEN CAPTURE SAVED TO DISK' });
    } catch(e) {
      EventBus.emit('sigint:log', { cat: 'CAPTURE', msg: 'CAPTURE FAILED — ' + e.message, level: 'warn' });
    }
  }

  return {
    init() {
      document.getElementById('btn-generate-report')?.addEventListener('click', _generate);
      document.getElementById('btn-screenshot')?.addEventListener('click', _screenshot);
    },
  };
})();
